spring:
  security:
    user:
      name: mintsso
      password: mintsso
      
server:
  port: 8091
      
eureka:
  instance:
    hostname: localhost #主机名
  client:
    register-with-eureka: false  #是否注册为服务
    fetch-registry: false #是否检索服务
  server:
    enableSelfPreservation: false #关闭自我保护(生产时打开该选项)
    eviction-interval-timer-in-ms: 5000 #扫描失效服务的间隔时间（缺省为60*1000ms）